# Generated by Django 3.2.3 on 2021-07-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=264)),
                ('Email', models.CharField(max_length=264)),
                ('PhoneNumber', models.CharField(max_length=264)),
                ('Address', models.CharField(max_length=264)),
                ('Organization', models.CharField(max_length=264)),
                ('Requirements', models.TextField()),
            ],
        ),
    ]
