# Generated by Django 3.2.3 on 2021-08-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='fullName',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='FirstName',
            field=models.CharField(default=1, max_length=264),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquiry',
            name='LastName',
            field=models.CharField(default=1, max_length=264),
            preserve_default=False,
        ),
    ]
